import ApiHttpClient from './api/ApiHttpClient';
import LoginService from './services/LoginService';
import ClienteService from './services/ClienteService';
import CobrancasService from './services/CobrancasService';
import LancamentoService from './services/LancamentoService';
import CupomDescontoService from './services/ecommerce/CupomDescontoService';
import CategoriaService from './services/CategoriaService';
import VendasPorCidadeService from './services/VendasPorCidadeService';
import GradesService from './services/GradesService';
import AreaAtuacaoService from './services/AreaAtuacaoService';
import CanaisVendaService from './services/CanaisVendaService';
import FormaEntregaService from './services/FormaEntregaService';
import ParametrosAplicativoService from './services/ecommerce/ParametrosAplicativoService';
import NotasFiscaisService from './services/NotasFiscaisService';
import SuggestionService from './services/SuggestionService';
import ProdutosService from './services/ProdutosService';
import CfopsService from './services/CfopsService';
import LambdaService from './services/LambdaService';
import ImportacaoXMLService from './services/ImportacaoXMLService';
import LocalizacaoService from './services/LocalizacaoService';
import NotificacoesAgendamentoService from './services/ecommerce/NotificacoesAgendamentoService';
import BoletoService from './services/BoletoService';
import BancoService from './services/BancoService';
import AtendimentosService from './services/AtendimentosService';
import PessoasService from './services/PessoasService';
import FinanceiroDespesaService from './services/FinanceiroDespesaService';
import MeioPagamentoService from './services/MeioPagamentoService';
import GrupoUsuarioService from './services/GrupoUsuarioService';
import EnderecosService from './services/EnderecosService';
import ProdutosHomepageService from './services/EcommerceProdutosHomepage';
import AtendimentoAgendaService from './services/AtendimentoAgendaService';
import IntegracaoApisService from './services/IntegracaoApisService';
import TransporteService from './services/TransporteService';
import RegrasNegociacaoService from './services/RegrasNegociacaoService';
import RegrasComissionamentoService from './services/RegrasComissionamentoService';
import PerfilPlanilhaDeDadosService from './services/PerfilPlanilhaDeDadosService';
import MedicamentosService from './services/MedicamentosService';
import FinanceiroReceitaService from './services/FinanceiroReceitaService';
import RemessaService from './services/RemessaService';
import RetornoService from './services/RetornoService';
import AtendimentoItensService from './services/AtendimentoItensService';
import ComissoesService from './services/ComissoesService';
import ConfiguracoesProcessoEmailService from './services/ecommerce/ConfiguracoesProcessoEmailService';
import ConfiguracoesFinanceiroService from './services/ConfiguracoesFinanceiroService';
import TimezonesService from './services/TimezonesService';
import OperacoesFiscaisService from './services/OperacoesFiscaisService';
import UnidadesNegocioService from './services/UnidadesNegocioService';
import TabelasPrecosProdutosService from './services/TabelasPrecosProdutosService';
import TabelasPrecosService from './services/TabelasPrecosService';
import ProdutoNcmService from './services/ProdutoNcmService';
import DadosTributariosService from './services/DadosTributariosService';
import ConfiguracoesAtendimentosService from './services/ConfiguracoesAtendimentoService';
import SistemaConfiguracoesService from './services/SistemaConfiguracoesService';
import GeralEnderecosService from './services/GeralEnderecosService';
import RelatorioService from './services/RelatorioService';
import EstoquesService from './services/EstoquesService';
import EstoqueMovimentacoesVeiculoService from './services/EstoqueMovimentacoesVeiculoService';
import RotasService from './services/RotasService';
import SistemaConfiguracoesPessoasService from './services/SistemaConfiguracoesPessoasService';
import ProdutosEstoquesService from './services/ProdutosEstoquesService';
import SistemaNotificacoesService from './services/SistemaNotificacoesService';
import TiposOperacoesService from './services/TiposOperacoesService';
import ResponsaveisVendasService from './services/ResponsaveisVendasService';

export default class Services {
  private static instance: Services;

  readonly httpClient: ApiHttpClient = new ApiHttpClient();
  readonly authHttpClient: ApiHttpClient = new ApiHttpClient(true);

  static get(): Services {
    if (this.instance == null) {
      this.instance = new Services();
    }

    return this.instance;
  }

  readonly loginService = new LoginService(this.httpClient);
  readonly relatorioService = new RelatorioService(this.authHttpClient);
  readonly financeiroReceitaService = new FinanceiroReceitaService(this.authHttpClient);
  readonly clienteService = new ClienteService(this.authHttpClient);
  readonly cobrancasService = new CobrancasService(this.authHttpClient);
  readonly lancamentoService = new LancamentoService(this.authHttpClient);
  readonly categoriaService = new CategoriaService(this.authHttpClient);
  readonly notificacoesAgendamentoService = new NotificacoesAgendamentoService(this.authHttpClient);
  readonly perfilPlanilhaDeDadosService = new PerfilPlanilhaDeDadosService(this.authHttpClient);
  readonly vendasPorCidadeService = new VendasPorCidadeService(this.authHttpClient);
  readonly responsaveisVendasService = new ResponsaveisVendasService(this.authHttpClient);
  readonly gradesService = new GradesService(this.authHttpClient);
  readonly areaAtuacaoService = new AreaAtuacaoService(this.authHttpClient);
  readonly canaisVendaService = new CanaisVendaService(this.authHttpClient);
  readonly formaEntregaService = new FormaEntregaService(this.authHttpClient);
  readonly cupomDescontoService = new CupomDescontoService(this.authHttpClient);
  readonly configuracoesProcessoEmailService = new ConfiguracoesProcessoEmailService(this.authHttpClient);
  readonly configuracoesFinanceiroService = new ConfiguracoesFinanceiroService(this.authHttpClient);
  readonly parametrosAplicativoService = new ParametrosAplicativoService(this.authHttpClient);
  readonly pessoasService = new PessoasService(this.authHttpClient);
  readonly notasFiscaisService = new NotasFiscaisService(this.authHttpClient);
  readonly suggestionService = new SuggestionService(this.authHttpClient);
  readonly produtosService = new ProdutosService(this.authHttpClient);
  readonly cfopsService = new CfopsService(this.authHttpClient);
  readonly atendimentosService = new AtendimentosService(this.authHttpClient);
  readonly lambdaService = new LambdaService(this.authHttpClient);
  readonly localizacaoService = new LocalizacaoService(this.authHttpClient);
  readonly financeiroDespesaService = new FinanceiroDespesaService(this.authHttpClient);
  readonly meioPagamentoService = new MeioPagamentoService(this.authHttpClient);
  readonly grupoUsuarioService = new GrupoUsuarioService(this.authHttpClient);
  readonly enderecosService = new EnderecosService(this.authHttpClient);
  readonly produtosHomepageService = new ProdutosHomepageService(this.authHttpClient);
  readonly transporteService = new TransporteService(this.authHttpClient);
  readonly regrasNegociacaoService = new RegrasNegociacaoService(this.authHttpClient);
  readonly regrasComissionamentoService = new RegrasComissionamentoService(this.authHttpClient);
  readonly boletosService = new BoletoService(this.authHttpClient);
  readonly remessaService = new RemessaService(this.authHttpClient);
  readonly retornoService = new RetornoService(this.authHttpClient);
  readonly bancoService = new BancoService(this.authHttpClient);
  readonly importacaoXMLProdutoService = new ImportacaoXMLService(this.authHttpClient);
  readonly estoqueMovimentacaoVeiculoService = new EstoqueMovimentacoesVeiculoService(this.authHttpClient);
  readonly atendimentoAgendaService = new AtendimentoAgendaService(this.authHttpClient);
  readonly IntegracaoApisService = new IntegracaoApisService(this.authHttpClient);
  readonly medicamentosService = new MedicamentosService(this.authHttpClient);
  readonly atendimentoItensService = new AtendimentoItensService(this.authHttpClient);
  readonly comissoesService = new ComissoesService(this.authHttpClient);
  readonly produtoNcmService = new ProdutoNcmService(this.authHttpClient);
  readonly timezonesService = new TimezonesService(this.authHttpClient);
  readonly unidadesNegocioService = new UnidadesNegocioService(this.authHttpClient);
  readonly dadosTributariosService = new DadosTributariosService(this.authHttpClient);
  readonly operacoesFiscaisService = new OperacoesFiscaisService(this.authHttpClient);
  readonly configuracoesAtendimentosService = new ConfiguracoesAtendimentosService(this.authHttpClient);
  readonly sistemaConfiguracoesService = new SistemaConfiguracoesService(this.authHttpClient);
  readonly geralEnderecosService = new GeralEnderecosService(this.authHttpClient);
  readonly tabelasPrecosService = new TabelasPrecosService(this.authHttpClient);
  readonly tabelasPrecosProdutosService = new TabelasPrecosProdutosService(this.authHttpClient);
  readonly estoquesService = new EstoquesService(this.authHttpClient);
  readonly rotasService = new RotasService(this.authHttpClient);
  readonly sistemaConfiguracoesPessoasService = new SistemaConfiguracoesPessoasService(this.authHttpClient);
  readonly produtosEstoquesServices = new ProdutosEstoquesService(this.authHttpClient);
  readonly sistemaNotificacoesService = new SistemaNotificacoesService(this.authHttpClient);
  readonly tiposOperacoesServices = new TiposOperacoesService(this.authHttpClient);
}
