enum MotivoDesoneracao {
  TAXI = 1,
  PRODUTO_AGROPECUARIO= 3,
  FROTISTA_LOCADORA,
  DIPLOMATICO_CONSULAR,
  UTILITARIOS_MOTOCICLETA,
  SUFRAMA,
  VENDA_ORGAO_PUBLICO,
  OUTROS,
  DEFICIENTE_CONDUTOR,
  DEFICIENTE_NAO_CONDUTOR,
  ORGAO_DESENVOLVIMENTO_AGROPECUARIO,
  SOLICITADO_FISCO= 90
}

export default MotivoDesoneracao;
